apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: docker.io/gmontalvoy/goapp:d980c48a08ef59a66b4bc34f84f1e5630c683149
        ports:
        - containerPort: 80
