name: Gathering changed files per commit per historification purposes
on:
  push:
    branches:
      - main
jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            tags: user/app:latest

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
            image: user/app:latest