name: Gathering changed files per commit per historification purposes
on:
  push:
    branches:
      - main
jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        run: |
          git diff --name-only HEAD^