name: Scan for vulnerabilities
on:
  push:
    branches:
      - main
jobs:
  Compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Container Scan
        uses: crazy-max/ghaction-container-scan@v3.0.0
        with:
          image: vulnerables/web-dvwa:latest
        