name: Release app
on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test the app
        run: go test -v ./...

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: goapp
          tags: ${{ github.run_number }}-dev
          containerfiles: |
            ./Dockerfile


  push-to-dev:
    name: Tag as dev and push
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: goapp
          tags: ${{ github.run_number }}-dev
          registry: docker.io/gmontalvoy
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      

  compliance:
    name: Image Scan
    needs: [ push-to-dev ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Image Scan
        uses: aquasecurity/trivy-action@0.15.0
        with:
          image-ref: 'docker.io/gmontalvoy/goapp:${{ github.run_number }}-dev'

  push-to-prod:
    name: push to registry
    needs: [ push-to-dev, compliance]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}