name: Release app
on:
  push:
    branches:
      - main

jobs:
  testCode:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test the app
        run: go test -v ./...

  build:
    name: Build and push to Docker Image
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: localhost:5000/gmontalvoy/goapp:${{ github.sha }}

  compliance:
    name: Image Scan
    needs: [ testCode, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Image Scan
        uses: aquasecurity/trivy-action@0.15.0
        with:
          image-ref: 'localhost:5000/gmontalvoy/goapp:${{ github.sha }}'

  push-to-registry:
    name: push to registry
    needs: [build, compliance]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: docker.io/gmontalvoy/goapp:${{ github.sha }}